# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: images.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cimages.proto\x12\x06images\"3\n\x05Image\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x0b\n\x03img\x18\x03 \x01(\x0c\"\x12\n\x10GetImagesRequest\"2\n\x11GetImagesResponse\x12\x1d\n\x06images\x18\x01 \x03(\x0b\x32\r.images.Image\"!\n\x13GetImageByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"4\n\x14GetImageByIdResponse\x12\x1c\n\x05Image\x18\x01 \x01(\x0b\x32\r.images.Image\"2\n\x12\x43reateImageRequest\x12\x1c\n\x05Image\x18\x01 \x01(\x0b\x32\r.images.Image\"3\n\x13\x43reateImageResponse\x12\x1c\n\x05Image\x18\x01 \x01(\x0b\x32\r.images.Image\"2\n\x12UpdateImageRequest\x12\x1c\n\x05Image\x18\x01 \x01(\x0b\x32\r.images.Image\"3\n\x13UpdateImageResponse\x12\x1c\n\x05Image\x18\x01 \x01(\x0b\x32\r.images.Image\" \n\x12\x44\x65leteImageRequest\x12\n\n\x02id\x18\x01 \x01(\t\"3\n\x13\x44\x65leteImageResponse\x12\x1c\n\x05Image\x18\x01 \x01(\x0b\x32\r.images.Image2\xf7\x02\n\x06Images\x12\x42\n\tGetImages\x12\x18.images.GetImagesRequest\x1a\x19.images.GetImagesResponse\"\x00\x12K\n\x0cGetImageById\x12\x1b.images.GetImageByIdRequest\x1a\x1c.images.GetImageByIdResponse\"\x00\x12H\n\x0b\x43reateImage\x12\x1a.images.CreateImageRequest\x1a\x1b.images.CreateImageResponse\"\x00\x12H\n\x0bUpdateImage\x12\x1a.images.UpdateImageRequest\x1a\x1b.images.UpdateImageResponse\"\x00\x12H\n\x0b\x44\x65leteImage\x12\x1a.images.DeleteImageRequest\x1a\x1b.images.DeleteImageResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'images_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGE']._serialized_start=24
  _globals['_IMAGE']._serialized_end=75
  _globals['_GETIMAGESREQUEST']._serialized_start=77
  _globals['_GETIMAGESREQUEST']._serialized_end=95
  _globals['_GETIMAGESRESPONSE']._serialized_start=97
  _globals['_GETIMAGESRESPONSE']._serialized_end=147
  _globals['_GETIMAGEBYIDREQUEST']._serialized_start=149
  _globals['_GETIMAGEBYIDREQUEST']._serialized_end=182
  _globals['_GETIMAGEBYIDRESPONSE']._serialized_start=184
  _globals['_GETIMAGEBYIDRESPONSE']._serialized_end=236
  _globals['_CREATEIMAGEREQUEST']._serialized_start=238
  _globals['_CREATEIMAGEREQUEST']._serialized_end=288
  _globals['_CREATEIMAGERESPONSE']._serialized_start=290
  _globals['_CREATEIMAGERESPONSE']._serialized_end=341
  _globals['_UPDATEIMAGEREQUEST']._serialized_start=343
  _globals['_UPDATEIMAGEREQUEST']._serialized_end=393
  _globals['_UPDATEIMAGERESPONSE']._serialized_start=395
  _globals['_UPDATEIMAGERESPONSE']._serialized_end=446
  _globals['_DELETEIMAGEREQUEST']._serialized_start=448
  _globals['_DELETEIMAGEREQUEST']._serialized_end=480
  _globals['_DELETEIMAGERESPONSE']._serialized_start=482
  _globals['_DELETEIMAGERESPONSE']._serialized_end=533
  _globals['_IMAGES']._serialized_start=536
  _globals['_IMAGES']._serialized_end=911
# @@protoc_insertion_point(module_scope)
